project:
  type: website

website:
  title: "Kwiz Computing Technologies"
  site-url: ""
  favicon: ""
  search: 
    location: navbar
    type: textbox
  navbar:
    logo: "/pages/images/logo/Kwiz_Inverted_Color.jpg"
    logo-alt: "Kwiz Computing Technologies"
    logo-href: "/index.qmd"
    background: "#e9945b"
    foreground: "#e9945b"
    pinned: true
    collapse: true
    right:
      - text: "Main Menu"
        menu:
          - text: "Home"
            href: index.qmd#Home
          - text: "Our Solutions"
            href: index.qmd#Solutions
          - text: "About Us"
            href: index.qmd#About
          - text: "Demos"
            href: index.qmd#Demos
          - text: "Testimonials"
            href: index.qmd#Testimonials

      - text: "Services"
        href: pages/services.qmd

        
      - text: "Resources"
        menu:
          - text: "Blogs"
            href: pages/resources.qmd#Blogs
          - text: "Tutorials"
            href: pages/resources.qmd#Tutorials

  page-footer: 
    background: "#1b4a9c"
    foreground: "#e9945b"
    left: "Copyright: Kwiz Computing Technologies Limited (2023)"
    right: 
      - "Created by: Kwiz Computing Technologies Limited" 
      - icon: github
        href: https://github.com/Kwiz-Computing-Technologies-Limited
      - icon: linkedin
        href: https://www.linkedin.com/company/kwizresearch/?viewAsMember=true
      - icon: whatsapp
        href: https://wa.link/ujtz0p

format:
  html:
    mainfont: nexaLight;
    css: styles.css
    toc: false

editor: visual

