project:
  type: website

website:
  title: "Kwiz Computing Technologies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/about.qmd
        text: About Us

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

