project:
  type: website

website:
  title: "Kwiz Computing Technologies"
  site-url: ""
  favicon: ""
  search: 
    location: navbar
    type: textbox
  navbar:
    logo: "/pages/images/logo/Kwiz_Inverted_Color.jpg"
    logo-alt: "Kwiz Computing Technologies"
    logo-href: "/index.qmd"
    background: "#e9945b"
    foreground: "#e9945b"
    pinned: true
    collapse: true
    right:
      - text: "Main Menu"
        menu:
          - href: index.qmd#Home
            text: Home
          - href: index.qmd#Solutions
            text: Our Solutions
          - href: index.qmd#About
            text: About Us
          - href: index.qmd#Demos
            text: Demos
          - href: index.qmd#Testimonials
            text: Testimonials
            
      - text: Services
        href: pages/services.qmd
        
      - text: Demos
        href: pages/demos.qmd
        
      - text: "Resources"
        menu:
          - href: pages/resources.qmd#Blogs
            text: Blogs
          - href: pages/resources.qmd#Tutorials
            text: Tutorials
      
  page-footer: 
    background: "#1b4a9c"
    foreground: "#e9945b"
    left: "Copyright: Kwiz Computing Technologies Limited (2023)"
    right: 
      - "Created by: Kwiz Computing Technologies Limited" 
      - icon: github
        href: https://github.com/Kwiz-Computing-Technologies-Limited
      - icon: linkedin
        href: https://www.linkedin.com/company/kwizresearch/?viewAsMember=true
      - icon: whatsapp
        href: https://wa.link/ujtz0p

format:
  html:
    mainfont: nexaLight;
    css: styles.css
    toc: false

editor: visual

