project:
  type: website

website:
  site-url: ""
  favicon: ""
  search: 
    location: navbar
    type: textbox
  navbar:
    title: "Kwiz Computing Technologies"
    logo: "/pages/images/logo/Kwiz_Inverted_Color.jpg"
    logo-alt: "Kwiz Computing Technologies"
    logo-href: "#Home"
    background: "#e9945b"
    foreground: "#e9945b"
    pinned: true
    collapse: false
    right:
      - href: "#Home"
        text: Home
      - href: "#Services"
        text: Our Solutions
      - href: "#About"
        text: About Us
      - href: "#Demos"
        text: Demos
      - href: "#Testimonials"
        text: Testimonials
      
        
  page-footer: 
    background: "#1b4a9c"
    foreground: "#e9945b"
    left: "Copyright: Kwiz Computing Technologies Limited (2023)"
    right: 
      - "Created by: Kwiz Computing Technologies Limited" 
      - icon: github
        href: https://github.com/Kwiz-Computing-Technologies-Limited
      - icon: linkedin
        href: https://www.linkedin.com/company/kwizresearch/?viewAsMember=true
      - icon: whatsapp
        href: https://wa.link/ujtz0p

format:
  html:
    mainfont: GeometrySoftPro;
    css: styles.css
    toc: false

editor: visual

