project:
  type: website

website:
  title: "Kwiz Computing Technologies"
  site-url: ""
  favicon: ""
  search: 
    location: navbar
    type: textbox
  navbar:
    logo: "/pages/images/logo/Kwiz_Inverted_Color.jpg"
    background: light
    right:
      - href: index.qmd
        text: Home
      - href: "#Services"
        text: Our Solutions
      - href: "#About"
        text: About Us
      - href: "#Demos"
        text: Demos
      - href: "#Testimonials"
        text: Testimonials
      
        
  page-footer: 
    center: "Created by: Kwiz Computing Technologies Limited" 
    left: "Copyright: Kwiz Computing Technologies Limited (2023)"
    right: 
      - icon: github
        href: https://github.com/Kwiz-Computing-Technologies-Limited
      - icon: linkedin
        href: https://www.linkedin.com/company/kwizresearch/?viewAsMember=true
      - icon: whatsapp
        href: https://wa.link/ujtz0p

format:
  html:
    mainfont: GeometrySoftPro;
    css: styles.css
    toc: false

editor: visual

