project:
  type: website

website:
  title: "Kwiz Computing Technologies"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: pages/about.qmd
        text: About Us
        
  page-footer: 
    center: "Created by: Kwiz Computing Technologies Limited" 
    left: "Copyright: Kwiz Computing Technologies Limited (2023)"
    right: 
      - icon: github
        href: https://github.com/Kwiz-Computing-Technologies-Limited
      - icon: linkedin
        href: https://www.linkedin.com/company/kwizresearch/?viewAsMember=true
      - icon: whatsapp
        href: https://wa.link/ujtz0p

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

